### ISSUE TITLE
Question - Connectivity to CTS700

### ISSUE THREAD

**Issue by kimthostrup** [wernerfred/docker-nilan-cts700#26]
Hi, 

First of all really cool project :)
May I ask you how you connect to the CTS700 board ? is that using the "LAN Cable" as described in the Nilan documentation ? or do you need to connect directly on the connectors on the print ?

Thanks in advance.
Kim

**Comment by wernerfred** [comment]
Hi Kim,
i plugged in the lan of the nilan (hanging around in the inside - next to the boiler) into powerlan and the other powerlan side directly into the router.
I have a server running with this container and provide the IP the nilan gets. Thats all.
From this point on you should see metrics served on: `http://<docker-host>:<prom-exporter-port>/metrics` which you can scrape by prometheus

**Comment by wernerfred** [comment]
Yeah but I only need this b/c I have no Ethernet in the room where Nilan is installed. If you have a switch or direct lan connection available you can simply plug it in

**Comment by kimthostrup** [comment]
Got it thanks 🙏🏻
