### ISSUE TITLE
Question - Modbus registers for CTS700

### ISSUE THREAD

**Issue by marcorigodanzo** [wernerfred/docker-nilan-cts700#36]
Hello
My name is Marco Rigodanzo, and I recently came across your GitHub project related to connecting to the Nilan Compact P CTS700 board. 🎉

I must say, good work! The way you’ve tackled the Nilan Compact P integration is valuable to the community. Kudos on creating such a cool project! 🌟

As I am working on an integration between a Nilan CTS700 and the home automation system Loxone, I was wondering if you could kindly share the Modbus registry manual or any relevant documentation that you referenced during your development. Your insights would be valuable to me, and I appreciate any assistance you can provide.

Thank you for your time, and I look forward to hearing from you!

**Comment by wernerfred** [comment]
Hi Marco, thanks for your warm words!
I have to dig deep into my archive but i think i downloaded (in some forum from a guy that contacted nilan support) a internal pdf with all those informations.
I'll try to find it in the next days and will share with you!

**Comment by marcorigodanzo** [comment]
Well I am ashamed to say that after googling like crazy, after finding a lot of outdated Pdf files that are not working anymore and after asking for your help I came across the right document that was in the most obvious place: the Nilan support site. 🤦‍♂️

Anyway I have attached the file I found, maybe you could add it to your project in case you (or someone) want to expand it with some other registers.

I have only one question: where did you get the register for the user_fan_speed? It is not present in the document that I have found

Thank you for your time and I am sorry to have bothered you!

[2018_04_Modbus_CTS700_Modbus_protokol.pdf](https://github.com/user-attachments/files/16058215/2018_04_Modbus_CTS700_Modbus_protokol.pdf)

**Comment by wernerfred** [comment]
Alright, found the file and quickly looked at the revision info. Seems to be the same version content wise, so i will not upload. Tried to search for the `user_fan_speed` but couln't find it in the pdf either. I remember that i did a lot of try & error getting a lot of values and then searching on the nilan display within the data output for the exakt values to actually get an idea what it shows. IIRC there were a lot of values that were not correct/not what the pdf states. E.g. the ones with the filter age never showed the correct values.

May i ask what you want to add within your project? So Loxone as target, i get it, but pls be so kind and share if you are missing further values so i could add them here as well as they might be valuable for others too.

**Comment by marcorigodanzo** [comment]
Hello Frederic
Thank you for your reply! I think what you did for the user_fan_speed was really remarkable, I would not be able to read it wouldn't it be for your trial & errors! as it is not in the PDF and I didn't find it anywhere else. 
By the way I was in no way suggesting that your project is not complete. I am just trying to get all the information that I can from the heat pump
Apart from the registries that you found, I was interested in 
- 21775 Compressor State
- 20103 Outdoor air filter Days to next filter change
- 20107 Extract air filter Days to next filter change
- 22490 Is any alarm or error present
- 21779 Fire alarm

I am also interested in the geo pump data and I need to locate the cooling setpoint, but I still have to understand exactly what are the correct registries for that.
I think I will try to understand what are mostly useful and then I will integrate them in the loxone app.
Thank you very much for your support!

**Comment by wernerfred** [comment]
Always happy to help, feel free to reach out in case of further questions
